### ISSUE TITLE
Error when "Combine CSS" is active

### ISSUE THREAD

**Issue by T4ngml** [umdevelopera/um-optimize#2]
Just gave a try to that extension

When loading the front end login page, the form's content won't render, and I get this error from the console:
<img width="596" alt="chrome_KWS7Gmq7L7" src="https://github.com/umdevelopera/um-optimize/assets/3415579/4a7a6b94-c3db-46b5-bbe3-09c4f2de5242">

This occurs only when Combine CSS is active.
I tried all the other combination settings: there's no issue as long as combine CSS is not ticked.
And the other way around, I always get this issue when it's ticked, whatever the other Optimize options are.

WordPress 6.4.3
UM 2.8.2 (tested also with 2.8.1 - same issue)
UM Optimize 1.1.1
No other cache / CSS/JS optimization active.

**Comment by vncntrcc** [comment]
I found the source of the error: 
class-assets.php:
   line 542 and 544 => copy paste error of CSS code. 
   modify CSS by JS

   line 271 => home_url() does not work for website root in a folder. 
   if your wordpress root is in a folder, combined CSS / JS are not generated.
   replace home_url() by site_url() solve this issue

**Comment by umdevelopera** [comment]
Thank you @vncntrcc 
I changed the _class-assets.php_ file like you suggested, see a369e58
Please update plugin to the version [1.1.2](https://github.com/umdevelopera/um-optimize/releases/tag/1.1.2)
