### ISSUE TITLE
Notification Bell

### ISSUE THREAD

**Issue by christophbill** [umdevelopera/um-optimize#5]
The notificationbell does not show on some pages.

**Comment by Izimartin** [comment]
Notification Bell Broken layout for all pages:

![image](https://github.com/user-attachments/assets/e6e70625-503a-4c71-a576-48ace1583abf)

**Comment by umdevelopera** [comment]
Hello @christophbill 
Thank you for pointing out this issue.
Notification Bell is displayed globally (on every page), so its CSS and JS files should not be removed. I added this as an exception.
